# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
