# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_documentcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Отображать на странице документов'),
        ),
    ]
