# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161215_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='published',
            field=models.BooleanField(verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
