# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161215_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, validators=[news.validators.no_future_date], verbose_name='Дата публикации'),
        ),
    ]
