# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('news', '0004_auto_20161216_0548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'ordering': ['-published_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='newspage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Person', verbose_name='Автор'),
        ),
    ]
