# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20161216_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
