# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newspage_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='announcement',
            field=models.TextField(help_text='Отображается вверху новости', max_length=200, verbose_name='Анонс'),
        ),
    ]
