# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20161220_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='announcement',
            field=models.TextField(help_text='Отображается вверху новости. Форматирование текста <b>не поддерживается.</b>', max_length=200, verbose_name='Анонс'),
        ),
    ]
