# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20161220_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('href', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание изображения')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='gallery',
        ),
        migrations.AddField(
            model_name='newspagegalleryimage',
            name='news_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsPage', verbose_name='Новость'),
        ),
    ]
