# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Добавлена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Добавлена')),
                ('published', models.BooleanField(verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='Адрес страницы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('full_width', models.BooleanField(default=False, help_text='Используется для слайдеров и карт', verbose_name='Секция во всю ширину')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Элемент страницы',
                'verbose_name_plural': 'Элементы страницы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Название слайдера')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на страницу')),
                ('background_image', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Slider', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Элемент слайдера',
                'verbose_name_plural': 'Элементы слайдера',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='slider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Slider', verbose_name='Слайдер'),
        ),
    ]
