# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20161215_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
