# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20161216_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.Person', verbose_name='Автор'),
        ),
    ]
