# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20161216_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('HOME', 'Главная страница'), ('ABOUT', 'Страница об организации'), ('ABOUT', 'Страница образование'), ('PAGE', 'Стандартная страница')], default='PAGE', max_length=500),
        ),
    ]
