# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20161217_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slider',
        ),
        migrations.AddField(
            model_name='slider',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Страница'),
        ),
    ]
