# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20161220_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Slider', verbose_name='Слайдер'),
        ),
    ]
