# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20161220_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на страницу')),
                ('background_image', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Элемент слайдера',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slider',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='SliderItem',
        ),
        migrations.AddField(
            model_name='pageslide',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Страница'),
        ),
    ]
