# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_documentsubcategory'),
        ('pages', '0010_auto_20161220_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='documents',
            field=models.ManyToManyField(blank=True, to='docs.Document', verbose_name='Документы'),
        ),
    ]
