# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_pagesection_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
