# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20170108_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='anchor',
            field=models.SlugField(blank=True, verbose_name='Якорная ссылка'),
        ),
        migrations.AlterUniqueTogether(
            name='pagesection',
            unique_together=set([]),
        ),
    ]
