# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20170109_0106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagesection',
            unique_together=set([]),
        ),
    ]
