# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_page_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Адрес страницы'),
            preserve_default=False,
        ),
    ]
