# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='name',
        ),
        migrations.AddField(
            model_name='organisation',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сокращенное наименование'),
        ),
    ]
