# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_organisation_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='director2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Директор'),
        ),
    ]
