# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organisation_director2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='director2',
        ),
    ]
