# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_organisation_director2'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('MAIN', 'Верхнее меню главной страницы'), ('FOOTER', 'Нижнее меню ')], default='MAIN', max_length=500, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menulink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organisationbuilding',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organisationfounder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
