# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('office', models.CharField(max_length=100, verbose_name='Кабинет')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование должности')),
                ('administration', models.BooleanField(default=False, verbose_name='Администрация')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='PersonTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вкладки')),
                ('content', models.TextField(verbose_name='Контент вкладки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Person', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Вкладка',
                'verbose_name_plural': 'Вкладки',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='positions',
            field=models.ManyToManyField(blank=True, to='staff.PersonPosition', verbose_name='Должности'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
