# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_document_created_at'),
        ('education', '0002_auto_20170105_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educourseannotation',
            name='course',
        ),
        migrations.AddField(
            model_name='educourse',
            name='annotations',
            field=models.ManyToManyField(blank=True, to='docs.Document', verbose_name='Должности'),
        ),
        migrations.AddField(
            model_name='educourse',
            name='learning_plane',
            field=models.FileField(blank=True, upload_to='docs/', verbose_name='Учебный план дисциплины'),
        ),
        migrations.DeleteModel(
            name='EduCourseAnnotation',
        ),
    ]
