# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_document_created_at'),
        ('education', '0003_auto_20170105_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educourse',
            name='learning_plane',
        ),
        migrations.AddField(
            model_name='educourse',
            name='course_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_program_docs', to='docs.Document', verbose_name='Рабочая программа дисциплины'),
        ),
        migrations.AlterField(
            model_name='educourse',
            name='annotations',
            field=models.ManyToManyField(blank=True, to='docs.Document', verbose_name='Аннотации рабочей программы дисциплины'),
        ),
    ]
