# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20170105_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educourse',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='course_annotations', to='docs.Document', verbose_name='Аннотации рабочей программы дисциплины'),
        ),
        migrations.AlterField(
            model_name='educourse',
            name='course_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='docs.Document', verbose_name='Рабочая программа дисциплины'),
        ),
    ]
