# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20170105_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduprogram',
            name='link',
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Страница образовательной программы'),
        ),
    ]
