# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_auto_20170108_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educourse',
            name='full_description',
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='full_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='educourse',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='eduprogram',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое Описание'),
        ),
    ]
