# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20170108_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='full_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Подробное описание'),
        ),
    ]
