# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20170108_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='description',
            field=models.CharField(blank=True, help_text='Например, автор программы.', max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='eduprogram',
            name='full_description',
            field=models.TextField(max_length=500, verbose_name='Подробное описание'),
        ),
    ]
