# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_auto_20170108_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educourse',
            name='description',
            field=models.CharField(blank=True, help_text='Вспомогательная информация, которая не видна посетителям сайта.', max_length=200, verbose_name='Описание'),
        ),
    ]
