# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_auto_20170108_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduprogram',
            name='full_description',
            field=models.TextField(blank=True, help_text='Отображается на странице образовательной программы.', max_length=500, verbose_name='Подробное описание'),
        ),
    ]
