# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_auto_20170108_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduprogram',
            old_name='url',
            new_name='slug',
        ),
    ]
